// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportService.Report.API.Infrastructure;

#nullable disable

namespace ReportService.Report.API.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20250510022353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneBookMicroservices.Shared.Models.ContactReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PhoneBookMicroservices.Shared.Models.ReportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalContacts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPhoneNumbers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactReportId");

                    b.ToTable("ReportDetails");
                });

            modelBuilder.Entity("PhoneBookMicroservices.Shared.Models.ReportDetail", b =>
                {
                    b.HasOne("PhoneBookMicroservices.Shared.Models.ContactReport", "ContactReport")
                        .WithMany("Details")
                        .HasForeignKey("ContactReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactReport");
                });

            modelBuilder.Entity("PhoneBookMicroservices.Shared.Models.ContactReport", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
